apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Optional: this component requires Prometheus Operator CRDs. It is deliberately
# not included by Tape's vanilla operator artifacts.
resources:
  - servicemonitor.yaml
  - prometheusrule.yaml
